export default [
    {
        id: 1,
        instruction: "A random number between 1 to 50 will be generated by the device."
    },
    {
        id: 2,
        instruction: "The goal of the game is to correctly guess the generated number."
    },
    {
        id: 3,
        instruction: "The player has 5 lives. 1 life is deducted for each wrong guess."
    },
    {
        id: 4,
        instruction: "To guess the number user can enter the number directly or press any of the three random numbers shown below the textbox."
    },
    {
        id: 5,
        instruction: "The three random numbers may or may not be the generated number."
    },
    {
        id: 6,
        instruction: "User can get any one digit of the number as a hint by pressing the '?' button."
    },
    {
        id: 7,
        instruction: "Using a hint will consume your 3 lives."
    },
    {
        id: 8,
        instruction: "The game ends when the correct number is guessed or when lives become 0."
    },
    {
        id: 9,
        instruction: "On ending, you can continue with number of lives left or restart the game with 5 lives."
    },
]