export default [
    {
        trackId: 1,
        artistName: "Desert Rock",
        albumName: "Wo Manzar",
        albumCoverUrl: "https://m.media-amazon.com/images/I/91xoVApSIrL._SS500_.jpg",
        songName: "Wo Manzar",
        songUrl: "",
    },
    {
        trackId: 2,
        artistName: "The Local Train",
        albumName: "Aalas ka Pedh",
        albumCoverUrl: "https://lastfm.freetls.fastly.net/i/u/ar0/be8c46d31aff51fca8076011407bf92a.jpg",
        songName: "Choo lo",
        songUrl: "",
    },
    {
        trackId: 3,
        artistName: "The Local Train",
        albumName: "Aalas ka Pedh",
        albumCoverUrl: "https://lastfm.freetls.fastly.net/i/u/ar0/be8c46d31aff51fca8076011407bf92a.jpg",
        songName: "Manzil",
        songUrl: "",
    },
    {
        trackId: 4,
        artistName: "The Local Train",
        albumName: "Vaaqif",
        albumCoverUrl: "https://i.pinimg.com/originals/c4/80/7f/c4807f89397a73e7c26ba514fd906812.jpg",
        songName: "Dilnawaz",
        songUrl: "",
    },
    {
        trackId: 5,
        artistName: "Mohit Chauhan",
        albumName: "Rockstar",
        albumCoverUrl: "https://images-na.ssl-images-amazon.com/images/I/91YtxtPbowL._RI_.jpg",
        songName: "Phir se ud chala",
        songUrl: "",
    },
    {
        trackId: 6,
        artistName: "Kodaline",
        albumName: "In a Perfect World",
        albumCoverUrl: "https://corcorantaylor.files.wordpress.com/2015/05/image.jpg",
        songName: "Talk",
        songUrl: "",
    },
    {
        trackId: 7,
        artistName: "Kygo, Sandro Cavazza",
        albumName: "Golden Hour",
        albumCoverUrl: "https://i2.wp.com/www.cultr.com/wp-content/uploads/2020/05/4orjko2axeu41.png?resize=696%2C696&ssl=1",
        songName: "Freedom",
        songUrl: "",
    },
    {
        trackId: 8,
        artistName: "Carly Rae Jepsen",
        albumName: "Cut to the feeling",
        albumCoverUrl: "https://i.scdn.co/image/966ade7a8c43b72faa53822b74a899c675aaafee",
        songName: "Cut to the feeling",
        songUrl: "",
    },
]