export default [
    {
        id: "1",
        artist: "Desert Rock",
        album: "Wo Manzar",
        artwork: "https://m.media-amazon.com/images/I/91xoVApSIrL._SS500_.jpg",
        title: "Wo Manzar",
        url: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3",
    },
    {
        id: "2",
        artist: "The Local Train",
        album: "Aalas ka Pedh",
        artwork: "https://lastfm.freetls.fastly.net/i/u/ar0/be8c46d31aff51fca8076011407bf92a.jpg",
        title: "Choo lo",
        url: "https://filesamples.com/samples/audio/mp3/sample1.mp3",
    },
    {
        id: "3",
        artist: "The Local Train",
        album: "Aalas ka Pedh",
        artwork: "https://lastfm.freetls.fastly.net/i/u/ar0/be8c46d31aff51fca8076011407bf92a.jpg",
        title: "Manzil",
        url: "https://filesamples.com/samples/audio/mp3/sample2.mp3",
    },
    {
        id: "4",
        artist: "The Local Train",
        album: "Vaaqif",
        artwork: "https://i.pinimg.com/originals/c4/80/7f/c4807f89397a73e7c26ba514fd906812.jpg",
        title: "Dilnawaz",
        url: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3",
    },
    {
        id: "5",
        artist: "Mohit Chauhan",
        album: "Rockstar",
        artwork: "https://images-na.ssl-images-amazon.com/images/I/91YtxtPbowL._RI_.jpg",
        title: "Phir se ud chala",
        url: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3",
    },
    {
        id: "6",
        artist: "Kodaline",
        album: "In a Perfect World",
        artwork: "https://corcorantaylor.files.wordpress.com/2015/05/image.jpg",
        title: "Talk",
        url: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3",
    },
    {
        id: "7",
        artist: "Kygo, Sandro Cavazza",
        album: "Golden Hour",
        artwork: "https://i2.wp.com/www.cultr.com/wp-content/uploads/2020/05/4orjko2axeu41.png?resize=696%2C696&ssl=1",
        title: "Freedom",
        url: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3",
    },
    {
        id: "8",
        artist: "Carly Rae Jepsen",
        album: "Cut to the feeling",
        artwork: "https://i.scdn.co/image/966ade7a8c43b72faa53822b74a899c675aaafee",
        title: "Cut to the feeling",
        url: "https://file-examples-com.github.io/uploads/2017/11/file_example_MP3_1MG.mp3",
    },
]